services:
  app:
    build: .
    stop_signal: SIGINT
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
      XDEBUG_MODE: ${XDEBUG_MODE}
    volumes:
      - app:/var/www/html
      - .:/var/www/html/wp-content/plugins/woocommerce-mercadopago
    ports:
      - ${APP_PORT}:80
    networks:
      - default
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - default
    depends_on:
      - db

volumes:
  db:
  app:
