/**
 * Testes unitarios para bin/check-css-reset.js (PSW-3603).
 *
 * Cobre TC-01 ate TC-18 conforme spec tecnica.
 * Fixtures inline; mocks de fs e process.exit para testar exit codes
 * sem encerrar o teste.
 */

const fs = require('fs');
const path = require('path');

const script = require('../../../bin/check-css-reset.js');

const {
  extractSelectorsFromJs,
  extractCoveredFromCss,
  extractInlineStyles,
  loadIgnoreRules,
  discoverBundleCssFiles,
  mergeCssData,
  findGaps,
  isBemMatch,
  generateSkeletonRule,
  injectSkeletonRules,
  alreadyHasAutoGenerated,
  run,
  AUTO_GENERATED_MARKER,
  SOURCE_STYLES,
  SOURCE_CLASSLIST,
  JS_PATH,
  CSS_PATH,
  CSS_DIR,
} = script;

// ─── Helpers ────────────────────────────────────────────────────────────────

function buildJsFixture(stylesEntries, hardcoded = []) {
  const pairs = Object.entries(stylesEntries)
    .map(([key, value]) => `    ${key}: '${value}'`)
    .join(',\n');
  const inline = hardcoded.map((c) => `elem.classList.add('${c}');`).join('\n');
  return `class Foo {\n  SUPER_TOKEN_STYLES = {\n${pairs}\n  }\n}\n${inline}\n`;
}

function buildCssRule(selector, properties) {
  const decls = Object.entries(properties)
    .map(([prop, value]) => `  ${prop}: ${value} !important;`)
    .join('\n');
  return `${selector} {\n${decls}\n}\n`;
}

const ROOT_SELECTORS = '#payment #mp-checkout-super-token-root, #payment-method #mp-checkout-super-token-root';

function makeTempProject(jsContent, cssContent, ignoreContent = null) {
  const tmp = fs.mkdtempSync(path.join(require('os').tmpdir(), 'css-reset-jest-'));
  const jsAbs = path.join(tmp, JS_PATH);
  const cssAbs = path.join(tmp, CSS_PATH);
  fs.mkdirSync(path.dirname(jsAbs), { recursive: true });
  fs.mkdirSync(path.dirname(cssAbs), { recursive: true });
  fs.writeFileSync(jsAbs, jsContent, 'utf8');
  fs.writeFileSync(cssAbs, cssContent, 'utf8');
  if (ignoreContent !== null) {
    fs.writeFileSync(path.join(tmp, '.css-reset-ignore'), ignoreContent, 'utf8');
  }
  return { tmp, jsAbs, cssAbs };
}

function cleanup(tmp) {
  if (fs.existsSync(tmp)) fs.rmSync(tmp, { recursive: true, force: true });
}

// ─── TC-01..TC-12: nucleo do gap analysis ───────────────────────────────────

describe('check-css-reset (TC-01..TC-12: core gap analysis)', () => {
  test('TC-01: JS com 3 classes, CSS cobre todas -> gaps = []', () => {
    const js = buildJsFixture({ A: 'mp-a', B: 'mp-b', C: 'mp-c' });
    const css =
      buildCssRule('.mp-a', { display: 'revert' }) +
      buildCssRule('.mp-b', { display: 'revert' }) +
      buildCssRule('.mp-c', { display: 'revert' });

    const jsSelectors = extractSelectorsFromJs(js);
    const cssData = extractCoveredFromCss(css);
    const gaps = findGaps(jsSelectors, cssData, []);

    expect(jsSelectors).toHaveLength(3);
    expect(gaps).toHaveLength(0);
  });

  test('TC-02: JS com 3 classes, CSS cobre 2 -> classe faltante e reportada', () => {
    const js = buildJsFixture({ A: 'mp-a', B: 'mp-b', C: 'mp-not-covered' });
    const css =
      buildCssRule('.mp-a', { display: 'revert' }) +
      buildCssRule('.mp-b', { display: 'revert' });

    const jsSelectors = extractSelectorsFromJs(js);
    const cssData = extractCoveredFromCss(css);
    const gaps = findGaps(jsSelectors, cssData, []);

    expect(gaps).toHaveLength(1);
    expect(gaps[0].className).toBe('mp-not-covered');
  });

  test('TC-03: classe no CSS mas nao no JS -> nao e gap', () => {
    const js = buildJsFixture({ A: 'mp-a' });
    const css =
      buildCssRule('.mp-a', { display: 'revert' }) +
      buildCssRule('.mp-orphan-css-only', { display: 'revert' });

    const gaps = findGaps(extractSelectorsFromJs(js), extractCoveredFromCss(css), []);
    expect(gaps).toHaveLength(0);
  });

  test('TC-04: classe BEM __modifier coberta pelo base -> sem gap', () => {
    const js = buildJsFixture({ MOD: 'mp-base__modifier' });
    const css = buildCssRule('.mp-base', { display: 'revert' });

    const gaps = findGaps(extractSelectorsFromJs(js), extractCoveredFromCss(css), []);
    expect(gaps).toHaveLength(0);
  });

  test('TC-05: CSS vazio -> classe sem regra específica e gap', () => {
    const js = buildJsFixture({ A: 'mp-a' });
    const cssData = extractCoveredFromCss('');
    expect(cssData.selectors).toHaveLength(0);

    const gaps = findGaps(extractSelectorsFromJs(js), cssData, []);
    // Sem CSS (sem wildcard, sem regra específica) → mp-a é gap
    expect(gaps).toHaveLength(1);
    expect(gaps[0].className).toBe('mp-a');
    // missingProperties = wildcardProps (vazio) → sugestão de esqueleto sem propriedades
    expect(gaps[0].missingProperties).toHaveLength(0);
  });

  test('TC-06: JS sem SUPER_TOKEN_STYLES -> lista vazia sem erro', () => {
    const js = 'const NOT_STYLES = { foo: "bar" };';
    const selectors = extractSelectorsFromJs(js);
    expect(selectors).toHaveLength(0);
  });

  test('TC-07: --ci com gaps -> exit code 1', () => {
    const js = buildJsFixture({ MISSING: 'mp-missing' });
    const css = buildCssRule('.mp-other', { display: 'revert' });
    const { tmp } = makeTempProject(js, css);

    try {
      const result = run({ projectRoot: tmp, mode: 'ci', io: { fs, log: () => {}, error: () => {} } });
      expect(result.exitCode).toBe(1);
      expect(result.gaps.length).toBeGreaterThan(0);
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-08: --ci sem gaps -> exit code 0', () => {
    const js = buildJsFixture({ A: 'mp-a' });
    const css = buildCssRule('.mp-a', { display: 'revert' });
    const { tmp } = makeTempProject(js, css);

    try {
      const result = run({ projectRoot: tmp, mode: 'ci', io: { fs, log: () => {}, error: () => {} } });
      expect(result.exitCode).toBe(0);
      expect(result.gaps).toHaveLength(0);
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-09: --fix com gaps -> regra esqueleto injetada no CSS', () => {
    const js = buildJsFixture({ MISSING: 'mp-needs-fix' });
    const css = buildCssRule('.mp-other', { display: 'revert', opacity: '1' });
    const { tmp, cssAbs } = makeTempProject(js, css);

    try {
      run({ projectRoot: tmp, mode: 'fix', io: { fs, log: () => {}, error: () => {} } });
      const updated = fs.readFileSync(cssAbs, 'utf8');
      expect(updated).toContain(AUTO_GENERATED_MARKER);
      expect(updated).toContain('gap detected for .mp-needs-fix');
      const [ctx1, ctx2] = ROOT_SELECTORS.split(',').map((s) => s.trim());
      expect(updated).toContain(`${ctx1} .mp-needs-fix`);
      expect(updated).toContain(`${ctx2} .mp-needs-fix`);
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-10: --fix idempotente -> CSS contem apenas 1 copia da regra', () => {
    const js = buildJsFixture({ MISSING: 'mp-needs-fix' });
    const css = buildCssRule('.mp-other', { display: 'revert', opacity: '1' });
    const { tmp, cssAbs } = makeTempProject(js, css);

    try {
      run({ projectRoot: tmp, mode: 'fix', io: { fs, log: () => {}, error: () => {} } });
      run({ projectRoot: tmp, mode: 'fix', io: { fs, log: () => {}, error: () => {} } });
      const updated = fs.readFileSync(cssAbs, 'utf8');
      const matches = updated.match(/gap detected for \.mp-needs-fix/g) || [];
      expect(matches).toHaveLength(1);
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-11: CSS com wildcard * scoped ao root — classe sem regra específica é gap com wildcardProps como sugestão', () => {
    const js = buildJsFixture({ A: 'mp-a' });
    const css =
      `#payment #mp-checkout-super-token-root.mp-super-token-payment-methods-list *,\n` +
      `#payment-method #mp-checkout-super-token-root.mp-super-token-payment-methods-list * {\n` +
      `  margin: 0 !important;\n` +
      `}\n` +
      buildCssRule('.mp-other', { display: 'revert' });

    const cssData = extractCoveredFromCss(css);
    expect(cssData.wildcardProperties).toContain('margin');
    expect(cssData.wildcardProperties).not.toContain('display');

    const gaps = findGaps(extractSelectorsFromJs(js), cssData, []);
    // mp-a tem regra específica? Não → gap
    expect(gaps).toHaveLength(1);
    // missingProperties = wildcardProperties (sugestão de esqueleto)
    // Wildcard cobre 'margin' → sugerida como propriedade a declarar explicitamente
    expect(gaps[0].missingProperties).toContain('margin');
    // 'display' é de .mp-other (regra específica), não do wildcard → NÃO aparece nas sugestões
    expect(gaps[0].missingProperties).not.toContain('display');
  });

  test('TC-12: classe hardcoded via classList.add e capturada', () => {
    const js = buildJsFixture({}, ['mp-super-token-error']);
    const selectors = extractSelectorsFromJs(js);
    const fromClassList = selectors.filter((s) => s.source === SOURCE_CLASSLIST);
    expect(fromClassList).toHaveLength(1);
    expect(fromClassList[0].className).toBe('mp-super-token-error');
  });

  test('TC-12b: className com múltiplas classes split corretamente', () => {
    const js = `div.className = 'mp-foo mp-bar';`;
    const selectors = extractSelectorsFromJs(js);
    const names = selectors.map((s) => s.className);
    expect(names).toContain('mp-foo');
    expect(names).toContain('mp-bar');
    expect(names).not.toContain('mp-foo mp-bar');
    expect(selectors).toHaveLength(2);
  });
});

// ─── TC-13..TC-17: .css-reset-ignore ────────────────────────────────────────

describe('check-css-reset (TC-13..TC-17: .css-reset-ignore)', () => {
  test('TC-13: classe no .css-reset-ignore (inteira) -> excluida do gap', () => {
    const js = buildJsFixture({ SKIP: 'mp-skip', OTHER: 'mp-other' });
    const css = buildCssRule('.mp-anchor', { display: 'revert' });
    const ignoreContent = 'mp-skip\n';
    const { tmp } = makeTempProject(js, css, ignoreContent);

    try {
      const rules = loadIgnoreRules(tmp);
      expect(rules).toHaveLength(1);
      expect(rules[0]).toEqual({ className: 'mp-skip', ignoredProperties: [] });

      const gaps = findGaps(extractSelectorsFromJs(js), extractCoveredFromCss(css), rules);
      expect(gaps.find((g) => g.className === 'mp-skip')).toBeUndefined();
      expect(gaps.find((g) => g.className === 'mp-other')).toBeDefined();
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-14: ignore parcial -> propriedades ignoradas excluidas de missingProperties (sugestão de esqueleto)', () => {
    const js = buildJsFixture({ X: 'mp-x' });
    // Wildcard cobre as 4 propriedades para todos os filhos do root
    const css =
      `#payment #mp-checkout-super-token-root.mp-super-token-payment-methods-list *,\n` +
      `#payment-method #mp-checkout-super-token-root.mp-super-token-payment-methods-list * {\n` +
      `  display: revert !important;\n` +
      `  box-shadow: none !important;\n` +
      `  visibility: visible !important;\n` +
      `  opacity: 1 !important;\n` +
      `}\n`;
    const ignoreContent = 'mp-x:display,box-shadow\n';
    const { tmp } = makeTempProject(js, css, ignoreContent);

    try {
      const rules = loadIgnoreRules(tmp);
      const gaps = findGaps(extractSelectorsFromJs(js), extractCoveredFromCss(css), rules);
      // mp-x não tem regra específica → gap
      expect(gaps).toHaveLength(1);
      // missingProperties = wildcardProps - ignoredProps
      // wildcardProps = [display, box-shadow, visibility, opacity]
      // ignoredProps  = [display, box-shadow]
      // resultado     = [visibility, opacity]
      const missing = gaps[0].missingProperties;
      expect(missing).not.toContain('display');
      expect(missing).not.toContain('box-shadow');
      expect(missing).toEqual(expect.arrayContaining(['visibility', 'opacity']));
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-15: .css-reset-ignore ausente -> script funciona normalmente', () => {
    const js = buildJsFixture({ A: 'mp-a' });
    const css = buildCssRule('.mp-a', { display: 'revert' });
    const { tmp } = makeTempProject(js, css);

    try {
      const rules = loadIgnoreRules(tmp);
      expect(rules).toEqual([]);
      const gaps = findGaps(extractSelectorsFromJs(js), extractCoveredFromCss(css), rules);
      expect(gaps).toHaveLength(0);
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-16: ignore parcial + wildcard — mp-x ainda é gap (sem regra específica), missingProperties = wildcardProps - ignored', () => {
    const js = buildJsFixture({ X: 'mp-x' });
    // Wildcard cobre visibility+opacity; .mp-anchor tem display+box-shadow (para outra classe)
    const css =
      `#payment #mp-checkout-super-token-root.mp-super-token-payment-methods-list *,\n` +
      `#payment-method #mp-checkout-super-token-root.mp-super-token-payment-methods-list * {\n` +
      `  visibility: visible !important;\n  opacity: 1 !important;\n` +
      `}\n` +
      buildCssRule('.mp-anchor', { display: 'revert', 'box-shadow': 'none' });

    const ignoreContent = 'mp-x:display,box-shadow\n';
    const { tmp } = makeTempProject(js, css, ignoreContent);

    try {
      const rules = loadIgnoreRules(tmp);
      const gaps = findGaps(extractSelectorsFromJs(js), extractCoveredFromCss(css), rules);
      // mp-x não tem regra específica → gap (lógica binária)
      // missingProperties = wildcardProps([visibility, opacity]) - ignored({display, box-shadow})
      // = [visibility, opacity] (display/box-shadow não fazem parte do wildcard aqui)
      expect(gaps).toHaveLength(1);
      expect(gaps[0].missingProperties).toEqual(expect.arrayContaining(['visibility', 'opacity']));
      expect(gaps[0].missingProperties).not.toContain('display');
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-17: linhas com # no .css-reset-ignore -> ignoradas como comentarios', () => {
    const js = buildJsFixture({ A: 'mp-a' });
    const css = buildCssRule('.mp-a', { display: 'revert' });
    const ignoreContent = '# this is a comment\n# another\nmp-foo\n# trailing\n';
    const { tmp } = makeTempProject(js, css, ignoreContent);

    try {
      const rules = loadIgnoreRules(tmp);
      expect(rules).toHaveLength(1);
      expect(rules[0].className).toBe('mp-foo');
    } finally {
      cleanup(tmp);
    }
  });
});

// ─── TC-18: extracao de inline styles ───────────────────────────────────────

describe('check-css-reset (TC-18: inline styles)', () => {
  test('TC-18: extracao de inline styles retorna InlineStyleUsage[] sem afetar gaps/exit', () => {
    const js = `
      elem.style.display = 'none';
      elem.style.height = '48px';
      other.style.display = 'flex';
    `;
    const usages = extractInlineStyles(js);
    expect(usages).toHaveLength(2);

    const display = usages.find((u) => u.property === 'display');
    const height = usages.find((u) => u.property === 'height');
    expect(display).toBeDefined();
    expect(height).toBeDefined();
    expect(display.occurrences).toBe(2);
    expect(display.lines).toHaveLength(2);
    expect(height.occurrences).toBe(1);

    // Confirma que nao gera gap nem altera exit code
    const cssData = extractCoveredFromCss('.mp-anchor { display: revert !important; }');
    const gaps = findGaps([], cssData, []);
    expect(gaps).toHaveLength(0);
  });

  test('TC-18b: camelCase convertido para kebab-case', () => {
    const js = `
      a.style.fontSize = '14px';
      b.style.boxShadow = 'none';
      c.style.backgroundColor = 'red';
    `;
    const usages = extractInlineStyles(js);
    const props = usages.map((u) => u.property).sort();
    expect(props).toEqual(['background-color', 'box-shadow', 'font-size']);
  });
});

// ─── TC-19: análise cross-file ──────────────────────────────────────────────

describe('check-css-reset (TC-19: cross-file bundle analysis)', () => {
  test('TC-19: classe coberta em arquivo secundário do bundle não é gap', () => {
    const js = buildJsFixture({ X: 'mp-x' });
    // arquivo A (principal): NÃO tem regra para mp-x
    const cssA = buildCssRule('.mp-other', { display: 'revert', opacity: '1' });
    // arquivo B (skeleton): TEM regra para mp-x
    const cssB = buildCssRule('.mp-x', { display: 'flex', opacity: '1' });

    const { tmp, cssAbs } = makeTempProject(js, cssA);

    try {
      // Criar um segundo arquivo CSS no mesmo diretório (simula bundle multi-file)
      const cssDir = path.dirname(cssAbs);
      const cssB_abs = path.join(cssDir, 'secondary-file.css');
      fs.writeFileSync(cssB_abs, cssB, 'utf8');

      // discoverBundleCssFiles encontra ambos os arquivos
      const bundleFiles = discoverBundleCssFiles(tmp, { fs });
      expect(bundleFiles).toHaveLength(2);

      // mergeCssData combina a cobertura
      const cssData = mergeCssData(bundleFiles.map((f) => extractCoveredFromCss(fs.readFileSync(f, 'utf8'))));

      // mp-x está coberta pelo arquivo B → não deve ser gap
      const gaps = findGaps(extractSelectorsFromJs(js), cssData, []);
      expect(gaps).toHaveLength(0);
    } finally {
      cleanup(tmp);
    }
  });

  test('TC-19b: run() inclui arquivos do bundle no relatório', () => {
    const js = buildJsFixture({ X: 'mp-x' });
    const cssA = buildCssRule('.mp-x', { display: 'revert' });
    const { tmp } = makeTempProject(js, cssA);

    try {
      const result = run({ projectRoot: tmp, mode: 'default', io: { fs, log: () => {}, error: () => {} } });
      // Com 1 arquivo → relatório menciona "1 file"
      expect(result.report).toContain('from 1 file');
    } finally {
      cleanup(tmp);
    }
  });
});

// ─── Helpers / extras ───────────────────────────────────────────────────────

describe('check-css-reset (helpers)', () => {
  test('isBemMatch: estritamente BEM, nao identico', () => {
    expect(isBemMatch('mp-base', 'mp-base__elem')).toBe(true);
    expect(isBemMatch('mp-base', 'mp-base--mod')).toBe(true);
    expect(isBemMatch('mp-base__elem', 'mp-base')).toBe(true);
    expect(isBemMatch('mp-base', 'mp-base')).toBe(false);
    expect(isBemMatch('mp-foo', 'mp-bar')).toBe(false);
  });

  test('generateSkeletonRule: dual-context + apenas missing + !important', () => {
    const rule = generateSkeletonRule('mp-test', ['display', 'opacity']);
    expect(rule).toContain('/* ' + AUTO_GENERATED_MARKER + ' gap detected for .mp-test');
    const [ctx1, ctx2] = ROOT_SELECTORS.split(',').map((s) => s.trim());
    expect(rule).toContain(`${ctx1} .mp-test`);
    expect(rule).toContain(`${ctx2} .mp-test`);
    expect(rule).toContain('display: revert !important;');
    expect(rule).toContain('opacity: 1 !important;');
    expect(rule).not.toContain('visibility:');
  });

  test('alreadyHasAutoGenerated: detecta marcador previo', () => {
    const css = `/* ${AUTO_GENERATED_MARKER} gap detected for .mp-x — missing: display */\n.mp-x { display: revert !important; }`;
    expect(alreadyHasAutoGenerated(css, 'mp-x')).toBe(true);
    expect(alreadyHasAutoGenerated(css, 'mp-y')).toBe(false);
  });

  test('injectSkeletonRules: idempotente sem mudar CSS existente', () => {
    const css = '.mp-anchor { display: revert !important; }\n';
    const gaps = [{ className: 'mp-new', missingProperties: ['display'] }];
    const r1 = injectSkeletonRules(css, gaps);
    expect(r1.injected).toBe(1);
    const r2 = injectSkeletonRules(r1.newContent, gaps);
    expect(r2.injected).toBe(0);
    expect(r2.skipped).toBe(1);
    expect(r2.newContent).toBe(r1.newContent);
  });
});

// ─── Mocks de fs e process.exit ─────────────────────────────────────────────

describe('check-css-reset (mocks fs + process.exit)', () => {
  let exitSpy;
  beforeEach(() => {
    exitSpy = jest.spyOn(process, 'exit').mockImplementation(() => {});
  });
  afterEach(() => {
    exitSpy.mockRestore();
    jest.restoreAllMocks();
  });

  test('arquivos ausentes -> exit code 1 sem encerrar o teste', () => {
    const tmpEmpty = fs.mkdtempSync(path.join(require('os').tmpdir(), 'css-reset-empty-'));
    try {
      const result = run({
        projectRoot: tmpEmpty,
        mode: 'default',
        io: { fs, log: () => {}, error: () => {} },
      });
      expect(result.exitCode).toBe(1);
    } finally {
      cleanup(tmpEmpty);
    }
  });
});
